name: Test

on: push

jobs:
  pytest:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        uv_resolution: ["highest", "lowest-direct"]

    env:
      UV_RESOLUTION: ${{ matrix.uv_resolution }}

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest
        env:
          PLEX_SERVER_NAME: ${{ secrets.PLEX_SERVER_NAME }}
          PLEX_TOKEN: ${{ secrets.PLEX_TOKEN }}
          IMDB_WATCHLIST_URL: ${{ vars.IMDB_WATCHLIST_URL }}
